import React, { Component } from "react";
import "./../assets/css/styles.css";

export default class AboutUs extends Component {
  render() {
    return (
      <main className="page landing-page">
        <section className="portfolio-block block-intro">
          <div className="container">
            <div className="p-2 mb-3 bg-light round-3">
              <div className="container-fluid py-5">
                <div className="row">
                  <div className="col m-4 ">
                    <h1 className="display-5 fw-bold welcome-h1 text-center">
                      About Us
                    </h1>
                    <br />
                    <p className="aboutus-p">
                      The DEAL (Data, Evidence and Learning) Strategy is a
                      project of{" "}
                      <a
                        href="https://theonn.ca/"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        ONN
                      </a>
                      ,{" "}
                      <a
                        href="https://www.ajah.ca/"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        Ajah
                      </a>{" "}
                      and{" "}
                      <a
                        href="https://poweredbydata.org/"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        Powered by Data
                      </a>{" "}
                      started with initial seed funding from{" "}
                      <a
                        href="https://www.otf.ca/"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        OTF
                      </a>
                      . The project is exploring different shared approaches of
                      connecting the Ontario nonprofit sector’s data and
                      knowledge in support learning and evidence-informed
                      decision-making. The objective of this project is to
                      support better programs and services, public policy
                      development, and outcomes for communities across Ontario.
                    </p>
                    <p className="aboutus-p">
                      As part of this project, Ajah explored building common,
                      open source infrastructure for the information already
                      available about the sector, focusing on existing open data
                      sources about nonprofit organizations, grants, and
                      evaluations. We think there is a lot of information that
                      is generated by the sector, but not made easily
                      accessible. We hope that this prototype will show the
                      benefits of open, sharable and organized data, as well as
                      allow different stakeholders to better understand the
                      organizations that make up our sector and the activities
                      and programs they run.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    );
  }
}
